FROM node:current-alpine3.11

WORKDIR /app

ENV PATH /app/node_modules/.bin:$PATH

COPY package.json /app
#COPY package-lock.json /app

RUN apk update && apk add bash
RUN npm install

# This helps avoid EACCES permission errors that can happen in Node images.
RUN chown -R node.node /app

COPY . ./