export const GET_INFO = 'GET_INFO';
export const GET_STATION = 'GET_STATION';
export const GET_LOCATION = 'GET_LOCATION';
export const UPDATE_LOCATION = 'UPDATE_LOCATION';
export const DATA_LOAD_SUCCESS = 'DATA_LOAD_SUCCESS';
export const REQUEST_DATA_LOAD = 'REQUEST_DATA_LOAD';