export const UPDATE_STATION_STATUS = 'UPDATE_STATION_STATUS';
export const GET_STATION_INFO = 'GET_STATION_INFO';
export const TOGGLE_FILTER = 'TOGGLE_FILTER';
export const UPDATE_QUERY = 'UPDATE_QUERY';
export const UPDATE_SEARCH = 'UPDATE_SEARCH';