export const UPDATE_STATION_STATUS = 'UPDATE_STATION_STATUS';
export const GET_STATION_INFO = 'GET_STATION_INFO';
export const TOGGLE_FILTER = 'TOGGLE_FILTER';
export const TOGGLE_OPTIONS = 'TOGGLE_OPTIONS';